server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:4567/Payment?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false

